### ISSUE TITLE
Example doesn't work on Android

### ISSUE THREAD

**Issue by LouisJS** [cpunion/react-native-actioncable#15]
Hi,

This repo have not been updated for a while, so out of precaution, i did try the repository and here is what i have so far : [Video Demo](https://wetransfer.com/downloads/7e4d3cab90892dcdcb13755cc64f242620180605145809/2bf42a)

The server works fine. We can see the message are correctly sent.
The message are also well received on iOS, but nothing happens on Android.

After adding some console.log, i've noticed the cable disconnected value is always true unlike on iOS.

Any idea ?

**Comment by LouisJS** [comment]
Ok. For the one who will face the same issue. The Android simulator nor Expo will have access to your WebSocket socket if you're using `localhost`.

Instead, get your IP : 
```ifconfig | grep "inet" | grep -v 127.0.0.1```

Change to `ws://localhost:3000/message` to `ws://10.67.x.x:3000/message`
It should now work on iOS, on Android, and even on Expo.

**Comment by masudhossain** [comment]
@LouisJS  were you able to get this to work on android? I'm having an issue getting it to work on android, but works fine in ios.

**Comment by masudhossain** [comment]
I'm using this with my live website in a server, and it's still showing up as disconnnected: true. http://prntscr.com/kpiuwh

**Comment by jorgeants** [comment]
In my case, in development environment just fine in both, iOS and Android, using IP rather than `localhost`. But in production environment don't work with Android.
